### PR TITLE
stream has to be disposed always otherwise the file is lock and cannot be replaced

### PR DESCRIPTION
**Pull request by GioviQ**

### CODE REVIEW

**Comment by thomaslevesque** [comment]
Hi @GioviQ,

Thanks, but... you didn't actually test this change, did you?
The stream needs to stay open while the animator is in use, because it will keep reading from it during the animation. The stream will be disposed when the animator is disposed. If you dispose it right after creating the animator, it will just throw an error as soon as it starts playing...

**Comment by GioviQ** [comment]
@thomaslevesque I am testing now and it works as expected. I used CacheFramesInMemory="True" too.
While the animation is running, I can update the gif file with a new version.

**Comment by GioviQ** [comment]
oops After a while it does not see anymore the gif, I will change File.Open instead

**Comment by thomaslevesque** [comment]
> I used CacheFramesInMemory="True"

In this case, yes, it might work. But by default this is false, and your change throws immediately when the GIF starts playing (I tried).

Anyway, not locking the file during playback was never a goal for this library. The original goal was to reduce memory usage, and for that I need to read for the file instead of holding the whole GIF in memory.

**Pull request closed without merging**
