### PR TITLE
Created XamlAnimatedGif and TestApp projects for .NET Core 3.1

### PR DESCRIPTION
**Pull request by VuleVuja**
Implementation of XamlAnimatedGif.WpfCore for .NET Core 3.1 based on XamlAnimatedGif.Wpf project
Created TestApp.WpfCore project for .NET Core 3.1 based on TestApp.Wpf project

### CODE REVIEW

**Comment by thomaslevesque** [comment]
Hi @VuleVuja,

Thanks for the PR. I appreciate the help, but please, don't send large PRs like this before discussing it with me first, because if it's not a change I want to make, you run the risk of having done the work for nothing...

As it happens, I *do* want to support .NET Core 3.1. The reason I haven't done it yet is that I have a few non-trivial decisions to make about the future of this project.

Currently, it supports many frameworks, but most of them are either de facto "dead", or officially out of support by Microsoft:
- Silverlight 5: Has been dead for a few years now
- .NET 4.0 : Out of support since 2016
- Windows 8.1: Everyone is trying to forget Windows 8. I'm not aware of anyone still writing apps for it.
- Windows Phone 8.1: Definitely dead; does anyone still write apps for Windows Phone?

So, this leaves:
- .NET 4.5 (which is technically out of support, but versions 4.5.2 and later are still supported)
- UWP (which isn't explicitly supported, but the Windows 8.1 code mostly works on UWP)

UWP now has native support for animated GIFs, which considerably reduces the need for XamlAnimatedGif (which has poor performance anyway). So, the only remaining framework that really benefits from XamlAnimatedGif is WPF.

So, my intention is to make a new major version that targets only WPF for net45 and netcoreapp3.1, and drop the rest. But I'll need to do some major refactoring, use multi-targeting, remove unused code, etc... I also need to consider what to do about my other similar project, WpfAnimatedGif; if XamlAnimatedGif now only supports WPF, there isn't much sense in having both projects, so I might reunite them.

All this to say that it wouldn't really make sense to merge your PR, because I'll probably have to restructure the whole project anyway...

**Comment by VuleVuja** [comment]
It's OK, I understand. I just needed it to work under .NET Core 3.1 since I'm migrating large application from .NET Framework 4.7.2. to .NET Core.

Looking forward for a new version of XamlAnimatedGif.

**Comment by thomaslevesque** [comment]
Have you tried referencing the current package directly from your .NET Core 3.1 project? I think it might just work... (I haven't tried it, though)

**Comment by VuleVuja** [comment]
No, I haven't. I can't do it right now. I'm trying to prepare as much projects as I can for .NET Core.
But, I tried to reference this .NET Core test app with the current package, and it works fine. Maybe it depends on stuffs installed on OS.
Thank you!

**Comment by thomaslevesque** [comment]
Since .NET Core 2 (I think), .NET Framework assemblies can be referenced from .NET Core apps. Of course it can fail at runtime if the assembly in question tries to call something that isn't available in .NET Core...

**Pull request closed without merging**
